name: pro_resume
description: This is a new portfolio website which will server purpose of online resume.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-67.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  path_provider: ^2.0.8
  syncfusion_flutter_pdfviewer: ^22.1.38
  flip_card: ^0.7.0
  modal_progress_hud_nsn: ^0.4.0
  url_launcher: ^6.0.18
  mailto: ^2.0.0
  share_plus: ^7.0.2
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.1
  percent_indicator: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: GoogleSansRegular
    fonts:
      - asset: assets/GoogleSansRegular.ttf
